#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    update-desktop-database /usr/share/applications || true
fi



exit 0
```

**debian/install:**
```
usr/bin/gofer-wrapper
usr/share/applications/gofer.desktop
